- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ ssh_user }}/.ssh"
    state: directory
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: '0700'

- name: Copy public SSH key to authorized_keys
  copy:
    src: "{{ ssh_public_key_file }}"
    dest: "/home/{{ ssh_user }}/{{ ssh_authorized_keys }}"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    mode: '0600'

- name: Set correct permissions on authorized_keys
  file:
    path: "/home/{{ ssh_user }}/{{ ssh_authorized_keys }}"
    mode: '0600'
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"