
- name: Configure SSH to disallow root login and use custom port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  when: not ansible_check_mode

- name: Ensure SSH Port is set
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Port"
    line: "Port {{ ssh_port }}"
  when: not ansible_check_mode

- name: Restart sshd
  service:
    name: ssh
    state: restarted
  when: not ansible_check_mode

- name: Install UFW firewall
  apt:
    name: ufw
    state: present
  when: not ansible_check_mode

- name: Allow needed ports
  ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ firewall_allowed_ports }}"
  when: not ansible_check_mode

- name: Enable UFW
  ufw:
    state: enabled
    immediate: yes
  when: not ansible_check_mode

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
  when: not ansible_check_mode

- name: Ensure fail2ban is running
  service:
    name: fail2ban
    state: started
    enabled: true
  when: not ansible_check_mode
