apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secrets
  namespace: forgejo
type: Opaque
stringData:
  DB_TYPE: postgres
  DB_HOST: forgejo-postgres
  DB_NAME: forgejo
  DB_USER: forgejo
  DB_PASSWD: forgejo_password

