# 00-devops-platform/kubernetes/apps/forgejo/forgejo-postgres.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-postgres
  namespace: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo-postgres
  template:
    metadata:
      labels:
        app: forgejo-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: forgejo-postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: forgejo-postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: forgejo-postgres-credentials
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}  # pour dev ; remplacer par PVC si besoin
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo-postgres
  namespace: forgejo
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app: forgejo-postgres
