apiVersion: v1
kind: Secret
metadata:
  name: forgejo-postgres-credentials
  namespace: forgejo
type: Opaque
stringData:
  POSTGRES_USER: forgejo
  POSTGRES_PASSWORD: forgejo_password
  POSTGRES_DB: forgejo