apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://codeberg.org/forgejo-contrib/forgejo-charts.git
    targetRevision: main
    path: charts/forgejo
    helm:
      valueFiles:
        - values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
