loki:
  persistence:
    enabled: false  
  config: |  
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h 
    ingester:
      wal:
        enabled: false
    schemaConfig:
      configs:
        - from: 2020-10-15
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storageConfig:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/cache
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
