kube-prometheus-stack:
  prometheusOperator:
    admissionWebhooks:
      enabled: false

  alertmanager:
    enabled: false

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      evaluationInterval: "30s"
      serviceMonitorSelector: {}
      retention: 10d

  grafana:
    enabled: true

  kubeStateMetrics:
    enabled: true

  nodeExporter:
    enabled: true

  prometheusRule:
    enabled: true

grafana:
  admin:
    password: admin
  service:
    type: ClusterIP
  ingress:
    enabled: false

loki:
  enabled: true
  useTestSchema: true        # <<< contourne l’erreur de schema_config
  persistence:
    enabled: false          # pas de persistence pour test

promtail:
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
