# values-prometheus.yaml
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    evaluationInterval: "30s"
    ruleSelector:
      matchLabels:
        role: alert-rules
    serviceMonitorSelector: {}
    retention: 10d

alertmanager:
  enabled: true

grafana:
  enabled: false  # on déploie Grafana séparément

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

# Exposer les alertes simples
prometheusRule:
  enabled: true
  additionalPrometheusRulesMap:
    basic-alerts: |
      groups:
        - name: basic.rules
          rules:
            - alert: KubernetesPodCrashLooping
              expr: increase(kube_pod_container_status_restarts_total[5m]) > 0
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: "Pod restarting frequently"
            - alert: HighCPUUsage
              expr: sum(rate(container_cpu_usage_seconds_total{image!=""}[2m])) by (namespace) > 0.8
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: "High CPU usage in namespace {{ $labels.namespace }}"
            - alert: HighMemoryUsage
              expr: sum(container_memory_usage_bytes{image!=""}) by (namespace) / sum(kube_namespace_annotations) # placeholder
              for: 2m
              labels:
                severity: warning
              annotations:
                summary: "High memory usage in namespace {{ $labels.namespace }}"
