apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "outline.fullname" . }}-data
  labels:
    app.kubernetes.io/name: {{ include "outline.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "5Gi" }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
