- name: Installer et configurer Nginx
  hosts: web
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer Nginx
      apt:
        name: nginx
        state: latest

    - name: Démarrer et activer Nginx
      service:
        name: nginx
        state: started
        enabled: yes
