name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: |
          pip install yamllint

      - name: Run yamllint on all YAML files
        run: |
          yamllint .

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Lint Forgejo chart
        run: |
          helm lint kubernetes/apps/forgejo

      - name: Lint Outline chart
        run: |
          helm lint kubernetes/apps/outline

      - name: Lint Monitoring chart
        run: |
          helm lint kubernetes/apps/monitoring

      # Optionnel : vérifier les manifests Kubernetes sans déployer
      - name: Install kubeconform
        run: |
          curl -sSL -o kubeconform https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64
          chmod +x kubeconform && sudo mv kubeconform /usr/local/bin/

      - name: Validate Kubernetes manifests
        run: |
          find kubernetes -type f -name '*.yml' -not -path '*/sops-gpg-config.yml' -exec kubeconform -summary {} +
