alertmanager:
    enabled: ENC[AES256_GCM,data:G4rUiE4=,iv:ffDXZo6AMLQ82KfTPNgRBD6x2heDrop8PTtEWru6SB4=,tag:onzB6jmNXKYbJhMgn5kiRg==,type:bool]
server:
    global:
        scrape_interval: ENC[AES256_GCM,data:fyI4,iv:PCeTs/9m7WAddyCP9xVFTxScnOz/50HWfeBF4vUaL2M=,tag:1w/RrOy9peWh2fFOr8348Q==,type:str]
    service:
        type: ENC[AES256_GCM,data:kg0e6SzsGbZ6,iv:Z+AvbBPkLKUTme+joA+fgsdZ36AAQOUslL1w3k87btY=,tag:M7p+6aRC14NK5aX4NpzkBA==,type:str]
    ingress:
        enabled: ENC[AES256_GCM,data:l1eAWA==,iv:8zlCt++I63MJ9ysA+hCPYyexkPUpjcNAo12oT/8Z+1I=,tag:QyhcdDGaSZhtkKLF7uKfqA==,type:bool]
        hosts:
            - ENC[AES256_GCM,data:JSi2xAUdNf7yUXwC1Lz9LQ==,iv:FYsrcWAB1vaw8nA093kx+W5SG5hu2uEWe0USRNy4OVg=,tag:u5s9Lw15pGv34mIPIws7Mg==,type:str]
        annotations:
            nginx.ingress.kubernetes.io/rewrite-target: ENC[AES256_GCM,data:Wg==,iv:6VnGdstXmz9UlhPabGBEVMRfqxIjKDN1yTBRToHJvTc=,tag:toLYKLYdSxNLWMzAvI7iXg==,type:str]
    resources:
        requests:
            memory: ENC[AES256_GCM,data:7+DB8tM=,iv:A+OTGodKG1iSJ6daxW/q0VvkswB8x2f9w2fYzLFgOME=,tag:iIJVQa70aFijmoEj5wNyTA==,type:str]
            cpu: ENC[AES256_GCM,data:PbEtOg==,iv:JFVnl13IF0r/I/pgvVlivmE3bq+XUYOtQzKY1CIrn0I=,tag:ryokudJzr2/jS9jAbcW/hg==,type:str]
        limits:
            memory: ENC[AES256_GCM,data:9INgNig=,iv:F9BzRVZURK/noPiHZ66/dqynyXeHSXxqU3+8SqYvIH8=,tag:2t+w0YXI0uJ8VYt45moEKw==,type:str]
            cpu: ENC[AES256_GCM,data:c/Yj1Q==,iv:xmHObYGdIyfj8vUmingS72WpqJgRNkj1wCcWkf0+Ev8=,tag:QZwm0Jtd4GDbkD7jqonMXw==,type:str]
rbac:
    create: ENC[AES256_GCM,data:DSHQWA==,iv:yq8Z4mm0S6ZtOlksG9mpWI9QYL5JsLST7C8SctR3yqE=,tag:PNSvproVL/kheGkuR1t2MQ==,type:bool]
serviceAccounts:
    server:
        create: ENC[AES256_GCM,data:GmVyZg==,iv:LP7iHiHK1YOQ8HXV7L7r4XHjWL4mnx1kX06Eztfb/gE=,tag:q5WMK252XecM9N7FLZLsAQ==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-29T12:57:15Z"
    mac: ENC[AES256_GCM,data:VZVZMH+fKkMlLmkJWov9+NNYogKl+qSyf7r8ArVkHAGWSbSH67ogyTn4Zgo4p8mUr6NPZj5e1HONMHo0hRa0W1SbD4VC6/zBjymIaAataYhsObMMS713GtXKgnZ6mWuVw339HxavA1aC7JFJQRERb8gjApV4WeBaQn+cPjH/cS8=,iv:fejFsVRKLQbOmQeN78ud0uShWNDxOMHSI9Z0WTs5yGg=,tag:KUVy5bUGeiD6kiHjm4vO5Q==,type:str]
    pgp:
        - created_at: "2025-07-29T12:57:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAzmtk14U8FJ/ARAApd8HmJOkhjIVwCFe/N7l9U4yl0k6neP5i3G+PF84Ucgr
            BctwJYdghnhScABmw7/igoT/aKkDrna2OReE1fjitlPbrFXYDE6ahZafQKNH83v2
            cinBlp58jnsXR+kQHKYvHASQg5amjGPvFUgnD5EX8emHhqTLRL8foVZCGZo7hdB0
            yZkm0omCCDW4GZtrXaE3RFpBf0rNFzChKIH1eXx53DR+cIi2GSlZ0jEN+7NuHFw+
            F65LxCWhhd8m4A4uYgUpDUEaVDInOwVchU6U3n0oMMqWNUZydD4O+5p2yT5G47Cy
            cagZy/C4GX46g1B64qjq8NYaBcWbIm7Dn1pxJE1ctvhhDZ1tpQLJAALxm9xJIguo
            oGpbfZT5rPBO9tlXaZUJ2xn0soqn6BlO9CZpsaX6ViMlCuIcSNj4Z1fLHwxUcERk
            HV6G8aHvjzeN80UwT0t792/p6N+TYqbWqtdtfsNJRXTiB22SKHrcrIf0FH+PdL12
            iJbRk9IYFwXZlESWIKczwd2bQcY85mugYfoFk0MeyQmzPczDuO+loevGFWl7kFux
            kat5jHr6nyyTLMQyNCoIlrozL939bDS8fzBMI4YeqvETo3nQtwOZb2gOizg4LpHL
            mdyfvL96trZkhobkCVf60iJ2VOvrvDXPjh/CnXe9H926Bti3qbxjehUSxcvb7qbU
            aAEJAhBcO6lB6Q2OPwky05dB8XxufqMbXS+05h4DLPb1677wjBjWwDOHIWsFsiMv
            RcefkqHpZeh543Q93xv6j4XqyCwKke6JAwmwxGlm+K+0F5MyD9EGh2SYy46tHF0T
            UhWsHh/gE28J
            =lOeQ
            -----END PGP MESSAGE-----
          fp: D9395B4A16F52E5EABCAEC19316DB02BD194EBEE
    unencrypted_suffix: _unencrypted
    version: 3.8.1
