grafana:
  service:
    type: LoadBalancer
  adminPassword: admin123
  defaultDashboardsEnabled: true
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
